server {

	listen 443 ssl;
	server_name app1.lab;
	ssl_certificate /etc/nginx/certs/cert.pem;
	ssl_certificate_key /etc/nginx/certs/key.pem;
	location / {
		proxy_pass http://web1;
	}

}

server {

	listen 443 ssl;
	server_name app2.lab;
	ssl_certificate /etc/nginx/certs/cert.pem;
	ssl_certificate_key /etc/nginx/certs/key.pem;
	location / {
		proxy_pass http://web2;
	}

}

server {

	listen 80;
	server_name app1.lab, app2.lab;
	return 301 https://$host$request_uri;	

}




